[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=development npm install && npm run db:generate --workspace=packages/database && npm run build --workspace=apps/bot"

[deploy]
startCommand = "node apps/bot/dist/index.js"
restartPolicyType = "always"
